# For debugging, you might want to enable
# LogLevel auth_openidc:debug


OIDCProviderMetadataURL "https://okta.umich.edu/oauth2/default/.well-known/openid-configuration"


# this is for client id and secret:
#  OIDCClientID
#  OIDCClientSecret
Include conf.d/secrets/oidc_secrets.conf

OIDCProviderTokenEndpointAuth client_secret_post
OIDCRedirectURI "https://<your-host-name.engin.umich.edu>/redirect_uri"
OIDCCacheType              shm

OIDCSessionCacheFallbackToCookie On
OIDCSessionInactivityTimeout 28800
OIDCSessionType server-cache
OIDCCacheEncrypt On
OIDCStateMaxNumberOfCookies 10 true

# use "openssl rand -hex 128" to generate the string below
OIDCCryptoPassphrase "somebigstring-from-rand-as-above"

OIDCScope "openid email"
OIDCRemoteUserClaim email

OIDCPreservePost On
OIDCUnAuthAction auth
OIDCUnAutzAction auth

# Turn on authentication for locations that require login
<Location /redirect_uri>
    AuthType openid-connect
    Require valid-user
</Location>

# Default to requiring authentication
<Location />
    AuthType openid-connect
    Require valid-user
</Location>

# Add any exception for public paths here a la
<Location "/public">
    AuthType None
    Require all granted
</Location>

# or if protected by IP a la
<Location "/ipprotected">
    Require ip 141.212.98.164 \
    141.213.175.240 \
    141.213.171.240
</Location>
