WSGISocketPrefix /usr/local/apache2/logs/wsgi
WSGIDaemonProcess mmra python-home=/usr python-path=/app
WSGIProcessGroup mmra
WSGIScriptAlias / /app/make_michigan_rest_api/wsgi.py
ServerName localhost

Alias /static/ /app/staticfiles/
<Directory /app/staticfiles>
    Require all granted
</Directory>

<Directory /app/make_michigan_rest_api>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>