# Generated by Django 6.0.6 on 2026-09-20 00:05

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSummary',
            fields=[
                ('pk', models.CompositePrimaryKey('recipient_user_id', 'credential_model_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.UUIDField()),
                ('credential_id', models.UUIDField()),
                ('credential_model_id', models.UUIDField()),
                ('credential_model_name', models.CharField(max_length=255)),
                ('credential_status', models.CharField(choices=[('active_user', 'active_user'), ('pending_user', 'pending_user'), ('operator', 'operator'), ('expired', 'expired'), ('invalidated', 'invalidated')], max_length=20)),
                ('author_first_name', models.CharField(max_length=100, null=True)),
                ('author_last_name', models.CharField(max_length=100, null=True)),
                ('completion_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('makerspace_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'credential_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCredentialModelPrerequisites',
            fields=[
                ('pk', models.CompositePrimaryKey('prerequisite_credential_model_name', 'dependent_credential_model_name', blank=True, editable=False, primary_key=True, serialize=False)),
                ('prerequisite_credential_model_name', models.CharField(max_length=255)),
                ('dependent_credential_model_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_credential_model_prerequisites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCredentialsAdmin',
            fields=[
                ('pk', models.CompositePrimaryKey('recipient_user_id', 'credential_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.UUIDField()),
                ('credential_id', models.UUIDField()),
                ('completion_date', models.DateField(null=True)),
                ('credential_model_name', models.CharField(max_length=255)),
                ('credential_status', models.CharField(choices=[('active_user', 'active_user'), ('pending_user', 'pending_user'), ('operator', 'operator'), ('expired', 'expired'), ('invalidated', 'invalidated')], max_length=20)),
                ('makerspace_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_credentials_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewEquipmentCards',
            fields=[
                ('equipment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('equipment_model_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=9)),
                ('rooms', models.JSONField(null=True)),
                ('equipment_type', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(null=True)),
                ('manufacturer_image_urls', models.JSONField(null=True)),
                ('materials', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'view_equipment_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewEquipmentDetailPages',
            fields=[
                ('equipment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('equipment_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('in_use', 'in_use'), ('reserved', 'reserved'), ('under_maintenance', 'under_maintenance'), ('out_of_order', 'out_of_order')], max_length=20, null=True)),
                ('materials', models.JSONField(null=True)),
                ('restricted_materials', models.JSONField(null=True)),
                ('in_situ_image_url', models.TextField(null=True)),
                ('last_serviced', models.DateTimeField(null=True)),
                ('equipment_specific_specs', models.JSONField(null=True)),
                ('notes', models.TextField(null=True)),
                ('equipment_model_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('specs_url', models.TextField(null=True)),
                ('is_cnc', models.BooleanField()),
                ('manufacturer_image_urls', models.JSONField(null=True)),
                ('capabilities', models.JSONField(null=True)),
                ('equipment_model_specific_specs', models.JSONField(null=True)),
                ('makerspace_id', models.UUIDField()),
                ('makerspace_name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=9)),
                ('rooms', models.JSONField(null=True)),
                ('credential_model_id', models.UUIDField(null=True)),
                ('credential_model_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'view_equipment_detail_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewIssueReportCards',
            fields=[
                ('issue_report_id', models.UUIDField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('is_resolved', models.BooleanField()),
                ('makerspace_id', models.UUIDField()),
                ('equipment_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('reporter_first_name', models.CharField(max_length=100, null=True)),
                ('reporter_last_name', models.CharField(max_length=100, null=True)),
                ('overseer_first_name', models.CharField(max_length=100, null=True)),
                ('overseer_last_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_issue_report_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMakerspaceCards',
            fields=[
                ('makerspace_id', models.UUIDField(primary_key=True, serialize=False)),
                ('makerspace_name', models.CharField(max_length=255)),
                ('cover_image', models.TextField(null=True)),
                ('building', models.CharField(max_length=9)),
                ('rooms', models.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('themes', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'view_makerspace_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMakerspaceDetailPages',
            fields=[
                ('makerspace_id', models.UUIDField(primary_key=True, serialize=False)),
                ('makerspace_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('makerspace_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('reserved', 'reserved'), ('soft_open', 'soft_open')], max_length=20, null=True)),
                ('cover_image', models.TextField(null=True)),
                ('building', models.CharField(max_length=9)),
                ('rooms', models.JSONField(null=True)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=10)),
                ('audience', models.JSONField(null=True)),
                ('themes', models.JSONField(null=True)),
                ('floorplan_image', models.TextField(null=True)),
                ('staff_ids', models.JSONField(null=True)),
                ('equipment_list', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'view_makerspace_detail_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewUserTrainings',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('uniqname', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('completed_trainings', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'user_trainings_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('capability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'capabilities',
            },
        ),
        migrations.CreateModel(
            name='CredentialModel',
            fields=[
                ('credential_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_model_name', models.CharField(max_length=255)),
                ('credential_type', models.CharField(choices=[('safety', 'safety'), ('equipment', 'equipment')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credential_models',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed'), ('in_use', 'in_use'), ('reserved', 'reserved'), ('under_maintenance', 'under_maintenance'), ('out_of_order', 'out_of_order')], max_length=20, null=True)),
                ('in_situ_image_url', models.TextField(blank=True, null=True)),
                ('specific_specs', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_serviced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('credential_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credentialmodel')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('equipment_model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_model_name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=100)),
                ('is_cnc', models.BooleanField()),
                ('specs_url', models.TextField(blank=True, null=True)),
                ('specific_specs', models.JSONField(blank=True, null=True)),
                ('manufacturer_image_urls', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment_models',
            },
        ),
        migrations.CreateModel(
            name='Makerspace',
            fields=[
                ('makerspace_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('makerspace_name', models.CharField(max_length=255)),
                ('makerspace_tier', models.CharField(blank=True, choices=[('basic', 'basic')], max_length=10, null=True)),
                ('makerspace_status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed'), ('reserved', 'reserved'), ('soft_open', 'soft_open')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rooms', models.JSONField(blank=True, null=True)),
                ('themes', models.JSONField(blank=True, null=True, validators=[core.models.validate_themes])),
                ('audience', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=10, validators=[core.models.validate_phone_length])),
                ('building', models.CharField(max_length=9)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('floorplan_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'makerspaces',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniqname', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('roles', models.JSONField(blank=True, default=list, validators=[core.models.validate_roles])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=10)),
                ('is_grad_student', models.BooleanField(default=False)),
                ('locale', models.CharField(choices=[('en_US', 'en_US'), ('en_GB', 'en_GB'), ('zh_CN', 'zh_CN'), ('es_ES', 'es_ES'), ('es_MX', 'es_MX'), ('es_LA', 'es_LA'), ('hi_IN', 'hi_IN'), ('ar', 'ar'), ('fr_FR', 'fr_FR'), ('fr_CA', 'fr_CA'), ('de_DE', 'de_DE'), ('ja_JP', 'ja_JP'), ('pt_BR', 'pt_BR'), ('pt_PT', 'pt_PT'), ('ru_RU', 'ru_RU')], default='en_US', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='CredentialModelPrerequisite',
            fields=[
                ('pk', models.CompositePrimaryKey('prerequisite_credential_model_id', 'dependent_credential_model_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dependent_credential_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_set', to='core.credentialmodel')),
                ('prerequisite_credential_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for_set', to='core.credentialmodel')),
            ],
            options={
                'db_table': 'credential_model_prerequisites',
            },
        ),
        migrations.CreateModel(
            name='OperationalData',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.equipment')),
                ('num_lifetime_reports', models.SmallIntegerField(blank=True, null=True)),
                ('lifetime_hours', models.IntegerField(blank=True, null=True)),
                ('monthly_users', models.SmallIntegerField(blank=True, null=True)),
                ('downtime', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operational_data',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentmodel'),
        ),
        migrations.CreateModel(
            name='EquipmentModelCapability',
            fields=[
                ('pk', models.CompositePrimaryKey('equipment_model_id', 'capability_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capability')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentmodel')),
            ],
            options={
                'db_table': 'equipment_model_capabilities',
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('issue_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='a', max_length=255)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('overseer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseen_issues', to=settings.AUTH_USER_MODEL)),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_reports',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.makerspace'),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_status', models.CharField(choices=[('active_user', 'active_user'), ('pending_user', 'pending_user'), ('operator', 'operator'), ('expired', 'expired'), ('invalidated', 'invalidated')], max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_credentials', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_credentials', to=settings.AUTH_USER_MODEL)),
                ('credential_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.credentialmodel')),
                ('issuing_makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.makerspace')),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='MakerspaceCredentialModel',
            fields=[
                ('pk', models.CompositePrimaryKey('makerspace_id', 'credential_model_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('credential_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.credentialmodel')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.makerspace')),
            ],
            options={
                'db_table': 'makerspace_credential_models',
            },
        ),
        migrations.CreateModel(
            name='MakerspaceStaff',
            fields=[
                ('pk', models.CompositePrimaryKey('makerspace_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.makerspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'makerspace_staff',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRestrictedMaterial',
            fields=[
                ('pk', models.CompositePrimaryKey('equipment_id', 'material_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
            options={
                'db_table': 'equipment_restricted_materials',
            },
        ),
        migrations.CreateModel(
            name='EquipmentAcceptedMaterial',
            fields=[
                ('pk', models.CompositePrimaryKey('equipment_id', 'material_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
            options={
                'db_table': 'equipment_accepted_materials',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_image_urls', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
