# Generated by Django 6.0.6 on 2026-09-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='makerspace',
            name='staff_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OperationalData',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
